### ISSUE TITLE
IE9 + IE10 scroll-to-zoom not working

### ISSUE THREAD

**Issue by Sholofly** [AndersDJohnson/magnificent.js#32]
Is it possible to fix scroll-to-zoom for IE9 and IE10? Using the mouse wheel on an image results in scrolling the entire page.

**Comment by adjohnson916** [comment]
@Sholofly Thanks for reporting the issue. I haven't had time to look into it yet. I believe the jQuery Mousewheel library does support these browsers, so not sure where it's failing. Any ideas? Pull requests welcome!

**Comment by Sholofly** [comment]
Hi Anders,

Thanks for your reply.

I didn't had the the time to investigate it yet, At the moment, i am busy
with a move to a new address, but after the move is complete i will take a
further look at it. In the meantime, if you have time, don't hesitate ;)



2015-09-11 1:30 GMT+02:00 Anders D. Johnson <notifications@github.com>:

**Comment by adjohnson916** [comment]
@Sholofly I've made some changes that seem to have somewhat improved these behaviors. Scroll-to-zoom and mouse positioning now seem to work for me in IE10. I've published the changes with `v2.1.3` to Bower and npm. Are you able to upgrade and confirm?

There still seem to be issues in IE10 with at least inner drag mode, and also I don't think my changes fixed anything in IE9 yet. I'm not sure if it's worth the effort to target IE9 though.

**Comment by liuzeyafzy** [comment]
"https://andrz.me/magnificent.js/examples/demo/"
Select the 'Inner' picture with Chrome Developer Tools, we can get ``<div class="mag-zone" ...></div>``. However, we get `` <img src="img/alley/500x300.jpg"/> `` in IE9 and IE10. 
I hope that'll be helpful.

**Comment by Sholofly** [comment]
Hi @adjohnson916,

Sorry for the late reply. Little bit busy woth other things ;) Thanks, i'm very happy with the current improvements. For now it's enough. Unfortunately i'm not able to spend more time testing your wonderful plugin. keep up the good wark and thanks again!

**Comment by adjohnson916** [comment]
@Sholofly Thanks. I'll still leave this open for now. IE 9 & 10 still have some market share.
