### ISSUE TITLE
Restore default zoom

### ISSUE THREAD

**Issue by warcraker** [AndersDJohnson/magnificent.js#51]
How can set by code the zoom and position to its defaults? That is, zoom: 100%, position: centered at [0, 0]

**Comment by AndersDJohnson** [comment]
@warcraker There are methods like `zoomTo` and `moveTo` with the jQuery plugin. I haven't looked at this for a while and don't recall exactly if the below is correct, but feel free to play with it and let me know.

```js
$('#mag').mag('zoomTo', 1)
$('#mag').mag('moveTo', { x: .5, y: .5 })
```

**Comment by warcraker** [comment]
That was exactly what I was looking for! 👍
I'll close it as resolved.

**Comment by warcraker** [comment]
By the way. There is any place where these commands are documented? In the demo there are examples for the constructor, but there is no info about other calls.
